### ISSUE TITLE
Error message need help

### ISSUE THREAD

**Issue by ghost** [boginw/zyxel-vmg8825-keygen#6]
Hello
I am having error message when sending command in xubuntu..
Can you please generate codes for this serial 

Thank you very much.

**Comment by boginw** [comment]
Hi @bougrinabil, thanks for taking an interest in this project.

I'd like to take the opportunity to tell you that it is probably not advisable to publish your serial number online, especially if it is combined with the supervisor's potential password.

However, since you've tried running the script and it gave you an error, I ran your serial number, and got the following output:

```
zcfgBeCommonGenKeyBySerialNum                   : WY7GWA8334
zcfgBeCommonGenKeyBySerialNum_CBT               : bee84dHb
zcfgBeCommonGenKeyBySerialNumMethod2            : bee84d2b
zcfgBeCommonGenKeyBySerialNumMethod3            : 69ReAqYvP4
zcfgBeCommonGenKeyBySerialNumConfigLength(1)    : 434734F4
zcfgBeCommonGenKeyBySerialNumConfigLength(2)    : Yb3AbPzu
zcfgBeCommonGenKeyBySerialNumConfigLength(3)    : yJmDbQTu
zcfgBeCommonGenKeyBySerialNumConfigLengthOld(1) : 434734F4
zcfgBeCommonGenKeyBySerialNumConfigLengthOld(2) : Yb3AbPzu
zcfgBeCommonGenKeyBySerialNumConfigLengthOld(3) : yJmDbQTu
```

If you have the ability, you should delete this issue whenever you've copied what you need :)

**Comment by ghost** [comment]
thank you very very much Sir.
